@startuml component_diagram
() "User"
() "Wifi"

node "ESP32" {
    component "Webserver"
    component "Audiomanager"
    component "Wifimanager"
    component "Sensormanager"
} 

component "Sensoren" {
    node "Distancesensor"
    node "Accelerationsensor" 
    node "Motionsensor"
}

node "Audio"{
    component "I²S"
    component "DAC"
    component "Bluetooth(Output, tracks, feedback)"
}

node "Web"{
    component "Web App"
    component "HTTP"
}

node "Devices"{
    component "Web application"
    component "WLAN Network"
    component "SWUOTA"
}

Audio-left->Audiomanager
Web-up->Webserver
Wifi-up-Wifimanager
User-right-Wifi
Sensoren-up->Sensormanager
@enduml