name: Firmware
run-name: Build Firmware Release

on:
  push:
    tags:
      - "v*.*.*"
      
permissions:
  contents: write
  actions: read
  checks: read
  deployments: read
  issues: read
  discussions: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build Firmware
        run: pio run -t mergebin -e wemos_d1_mini32

      - name: Build Filesystem
        run: pio run -t buildfs -e wemos_d1_mini32

      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          files: |
            .pio/build/wemos_d1_mini32/firmware.bin
            .pio/build/wemos_d1_mini32/littlefs.bin
            .pio/build/wemos_d1_mini32/system.bin

      #- name: Upload Firmware
       # uses: actions/upload-artifact@v4
        #with:
         # path: .pio/build/wemos_d1_mini32/firmware.bin
          #name: firmware
